/*******************************************************************************
* Version                   Date                  Name               Description
* ==============================================================================
* V1.0                      22-03-2021            Developper1        Add
*
*********************************************************************************
public with sharing class calculator {
    public calculator() {

    }
    public integer add(integer a, integer b){
        return a+b;

}